# Generated by Django 3.2 on 2022-03-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Bitcoin Price',
                'verbose_name_plural': 'Bitcoin Price',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_path', models.CharField(max_length=254)),
            ],
        ),
    ]
