# Generated by Django 3.2 on 2022-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Bitcoin Price',
                'verbose_name_plural': 'Bitcoin Price',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('is_premium_metric', models.BooleanField()),
                ('image_path', models.CharField(max_length=254)),
            ],
        ),
    ]
