# Generated by Django 3.2 on 2022-01-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_bitcoin_price_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=254)),
                ('value', models.FloatField(verbose_name='value')),
            ],
        ),
    ]
