# Generated by Django 3.2 on 2022-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metric_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric_data',
            name='value',
        ),
        migrations.AddField(
            model_name='metric_data',
            name='ma200w',
            field=models.FloatField(blank=True, null=True, verbose_name='200WMA'),
        ),
        migrations.AddField(
            model_name='metric_data',
            name='ma50D_50w',
            field=models.FloatField(blank=True, null=True, verbose_name='ma50D_50w'),
        ),
        migrations.AddField(
            model_name='metric_data',
            name='pi_cycle_top',
            field=models.FloatField(blank=True, null=True, verbose_name='pi_cycle_top'),
        ),
        migrations.AddField(
            model_name='metric_data',
            name='risk_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='risk_indicator'),
        ),
        migrations.AddField(
            model_name='metric_data',
            name='rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='rsi'),
        ),
        migrations.AlterField(
            model_name='metric_data',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
