# Generated by Django 3.2 on 2022-01-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20220105_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric_data',
            old_name='ma50D_50w',
            new_name='ma50d_50w',
        ),
        migrations.RemoveField(
            model_name='metric_data',
            name='rsi',
        ),
    ]
