# Generated by Django 3.2 on 2022-01-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_bitcoin_price_data_id'),
        ('metrics', '0006_auto_20220105_2121'),
    ]

    operations = [
    ]
