# Generated by Django 3.2 on 2022-01-16 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_merge_20220113_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
