# Generated by Django 3.2 on 2022-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_auto_20220116_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('price', models.FloatField(verbose_name='price')),
            ],
        ),
        migrations.DeleteModel(
            name='Bitcoin_Price_Data',
        ),
        migrations.DeleteModel(
            name='Metric_Data',
        ),
    ]
