# Generated by Django 3.2 on 2022-02-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_auto_20220208_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitcoinpricedata',
            options={'verbose_name': 'Bitcoin Price Data', 'verbose_name_plural': 'Bitcoin Price Data'},
        ),
    ]
